### ISSUE TITLE
failed  CalledProcessError

### ISSUE THREAD

**Issue by BaymaxTong** [google/nogotofail#116]
Hi  ngtf,
Can you please help me to fix this problem.

$sudo python -m nogotofail.mitm --mode tproxy --serverssl server.crt

2017-07-24 22:11:10,976 [INFO] Starting...
2017-07-24 22:11:11,433 [ERROR] Failed to setup routing rules
Traceback (most recent call last):
  File "nogotofail/mitm/util/routing.py", line 83, in enable_tproxy_rules
    add_local_bypass("mangle", TPROXY_CHAIN, ipv6)
  File "nogotofail/mitm/util/routing.py", line 59, in add_local_bypass
    ipv6=False)
  File "nogotofail/mitm/util/routing.py", line 35, in run_iptables_cmd
    run_command(ipv4_bin + " " + command, ignore_failed)
  File "nogotofail/mitm/util/routing.py", line 28, in run_command
    raise e
CalledProcessError: Command 'iptables -t mangle -A ngtf_mangle_PREROUTING -p tcp -d 地址:127.0.0.1 -j RETURN' returned non-zero exit status 2
2017-07-24 22:23:31,104 [INFO] Blame: New client from 10.0.0.8
2017-07-24 22:23:46,183 [INFO] Blame: Client 10.0.0.8 closed connection
2017-07-24 22:23:46,220 [INFO] Blame: New client from 10.0.0.8

**Comment by BaymaxTong** [comment]
I solved the problem
